# Generated by Django 5.1.2 on 2024-11-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Catagory',
            new_name='Category',
        ),
    ]
