# Generated by Django 5.1.2 on 2024-11-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
